#!/bin/bash

# Connect docker-compose to boot2docker
eval "$(docker-machine env default)"

# By default the boot2docker vm docker-machine sets up wants to use
# corp.localytics.com resolvers which I can't get at home
docker-machine ssh default "echo nameserver 8.8.8.8 > /etc/resolv.conf"

# Build the containers that are not pulled images
docker-compose build

# Tag containers with :latest for pushing; push to Docker Hub
docker tag -f slact_go bjacobel/slact_go:latest
docker push bjacobel/slact_go

docker tag -f slact_caddy bjacobel/slact_caddy:latest
docker push bjacobel/slact_caddy

# Tell ECS who I am and what cluster to use
ecs-cli configure \
  --region us-east-1 \
  --profile bjacobel \
  --cluster slact

# Get the name of my security group, my active AZs, my VPC and its subnets. Requires jq
VPC=$(aws --profile bjacobel ec2 describe-vpcs \
  | jq -r '.Vpcs[0].VpcId')

USEAST1B_SUBNET=$(aws ec2 --profile bjacobel describe-subnets \
  --filters Name=vpc-id,Values=$VPC \
  --filters Name=availability-zone,Values=us-east-1b \
  | jq -r '.Subnets[0].SubnetId')

USEAST1C_SUBNET=$(aws ec2 --profile bjacobel describe-subnets \
  --filters Name=vpc-id,Values=$VPC \
  --filters Name=availability-zone,Values=us-east-1c \
  | jq -r '.Subnets[0].SubnetId')

SG=$(aws --profile bjacobel ec2 describe-security-groups \
  --filters Name=vpc-id,Values=$VPC \
  --filters Name=ip-permission.protocol,Values=tcp \
  --filters Name=ip-permission.from-port,Values=80,443 \
  | jq -r '.SecurityGroups[0].GroupId')

# Spin up an ECS cluster if one doesn't already exist
ecs-cli up \
  --capability-iam \
  --keypair ecs \
  --size 1 \
  --instance-type t2.micro \
  --vpc $VPC \
  --azs us-east-1b,us-east-1c \
  --subnets $USEAST1B_SUBNET,$USEAST1C_SUBNET \
  --security-group $SG \
|| { echo "ECS cluster already exists, or something awful happened."; }

# Template a config file with secrets from .env
export $(cat .env)
command -v /usr/local/Cellar/gettext/0.19.6/bin/gettext >/dev/null 2>&1 || { brew install https://raw.githubusercontent.com/Homebrew/homebrew/8fc48e88e959848be4e7edc8528092634603956b/Library/Formula/gettext.rb; }
/usr/local/Cellar/gettext/0.19.6/bin/envsubst < docker/docker-compose-prod.yml > docker/docker-compose-prod.tmp.yml

# Push to ECS and bring the containers up
ecs-cli compose \
  --file docker/docker-compose-prod.tmp.yml \
  up

# Remove the config file with secrets in it
rm docker/docker-compose-prod.tmp.yml
