#!/bin/sh

docker-compose build

docker tag slact_go bjacobel/slact_go:latest
docker push bjacobel/slact_go

docker tag slact_nginx bjacobel/slact_nginx:latest
docker push slact_nginx bjacobel/slact_nginx

ecs-cli configure \
  --region us-east-1
  --profile bjacobel
  --cluster slact

ecs-cli compose \
  --verbose \
  --file docker/docker-compose-prod.yml \
  --project-name slact \
  up
