caddy:
  image: jumanjiman/caddy:latest
  links:
    - go
  ports:
    - 80:80
  volumes:
    - ./docker/caddy:/etc/caddy
  command: -conf /etc/caddy/Caddyfile
  container_name: slact_caddy
  labels:
    app: slact
go:
  build: .
  links:
    - mongo
  expose:
    - 3000
  env_file:
    - .env
  environment:
    - MGHOST=mongo
  container_name: slact_go
  labels:
    app: slact
mongo:
  image: mongo:3.2
  command: --quiet
  container_name: slact_mongo
  labels:
    app: slact
