nginx:
  container_name: slact_nginx
  links:
    - go
  ports:
    - "80:80"
    - "443:443"
  build: ./docker/nginx
go:
  container_name: slact_go
  build: .
  expose:
    - "3000"
  env_file:
    - .env
