nginx:
  image: bjacobel/slact_nginx:latest
  links:
    - go
  ports:
    - "80:80"
    - "443:443"
  mem_limit: 128000000
go:
  image: bjacobel/slact_go:latest
  environment:
    - MGHOST=${MGHOST}
    - MGDB=${MGDB}
    - MGCOLL=${MGCOLL}
    - MGPW=${MGPW}
    - MGUSER=${MGUSER}
    - SLACK=${SLACK}
  links:
    - mongo
  mem_limit: 64000000
mongo:
  image: mongo:3.2
  mem_limit: 128000000
