caddy:
  image: bjacobel/slact_caddy:latest
  links:
    - go
  ports:
    - "80:80"
    - "443:443"
  command: "--conf=/etc/caddy/Caddyfile-prod"
  mem_limit: 128000000
go:
  image: bjacobel/slact_go:latest
  links:
    - mongo
  environment:
    - MGHOST=${MGHOST}
    - MGDB=${MGDB}
    - MGCOLL=${MGCOLL}
    - MGPW=${MGPW}
    - MGUSER=${MGUSER}
    - SLACK=${SLACK}
  mem_limit: 64000000
mongo:
  command: "--quiet"
  image: mongo:3.2
  mem_limit: 128000000
